name: Django                                  # workflow name

on:
  push:                                       
    branches:                                 # similar to "only" in GitLab
      - main

jobs:
  build:
    runs-on: ubuntu-latest                    # similar to "image" in GitLab
    steps:
      - run: echo "This is a build step"      # similar to "script" in GitLab

  test:
    needs: build              # run after build
    runs-on: ubuntu-latest
    steps:
      - run: echo "This is a test step"
      - run: echo “hello” > hello.txt
      - name: save artifact "hello"         # saves the artifact hello.txt created in the run section          
        uses: actions/upload-artifact@v2
        with:
          name: hello
          path: hello.txt

  integration:
    needs : [build, test]         #run after build and test
    continue-on-error: true      #continue even if it exits with 1
    runs-on: ubuntu-latest
    steps:
      - run: echo "This is an integration step"
      - run: exit 1
      

  prod:
    needs: [build, test, integration]         # run after build test and integration
    runs-on: ubuntu-latest
    steps:
      - run: echo "This is a deploy step"
